#!/usr/bin/env python3
"""
knowledge_index.py — 由條目 metadata 重生 knowledge INDEX(生成物,不手維護)

拆檔模式(docs/knowledge/entries/ 一條目一檔)下,INDEX 若靠手維護必然漂移;本腳本把
INDEX.md 變成「生成物」:掃描條目、抽 metadata、重寫 docs/knowledge/INDEX.md。
排序:user-confirmed(DIR)→ deep → shallow → 其他;同層按 id。跳過 entries/archive/。

用法:
  python3 knowledge_index.py --repo .            # 重生 docs/knowledge/INDEX.md
  python3 knowledge_index.py --repo . --check    # 只驗新鮮:現存 INDEX 與重生結果不符 → exit 1

退出碼:0 = 成功/新鮮;1 = --check 發現過期(或無 INDEX);2 = 參數/環境錯誤。
"""
from __future__ import annotations
import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# 釘住輸出編碼(CHG-20260803-01 T1):不依賴主控台/locale 的 ambient 編碼。
# 非 UTF-8 主控台(如 Windows cp932)印 CJK/emoji 會 UnicodeEncodeError;
# 釘住後同一份程式在任何平台的輸出行為一致。errors="replace" 確保永不因輸出而崩潰。
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")

HEAD_RE = re.compile(r"^#{1,2}\s*((?:KN|DIR)-[\w.]+)\s*[—-]\s*(.+)$", re.MULTILINE)
TIER_RE = re.compile(r"tier\s*[::]\s*(shallow|deep)", re.IGNORECASE)
CONF_RE = re.compile(r"(使用者確認|user-confirmed)", re.IGNORECASE)
TAGS_RE = re.compile(r"tags/scope\s*[::]\s*(.+)")
STATUS_RE = re.compile(r"(狀態|status)\s*[::]\s*(.+)", re.IGNORECASE)
COUNT_RE = re.compile(r"(計數|counters)\s*[::]\s*(.+)", re.IGNORECASE)

GEN_MARK = "<!-- generated by knowledge_index.py — do not edit by hand / 生成物,勿手改 -->"


def parse_entry(f: Path) -> dict:
    text = f.read_text(encoding="utf-8", errors="ignore")
    m = HEAD_RE.search(text)
    eid = m.group(1) if m else f.stem
    rule = (m.group(2).strip() if m else "").split("\n")[0][:80] or "—"
    if eid.upper().startswith("DIR") or CONF_RE.search(text):
        tier = "user-confirmed"
    else:
        tm = TIER_RE.search(text)
        tier = tm.group(1).lower() if tm else "shallow"
    tm2 = TAGS_RE.search(text)
    tags = (tm2.group(1).strip().split("——")[0].split("—")[0].strip() if tm2 else "—")
    st = STATUS_RE.search(text)
    status = st.group(2).strip()[:40] if st else "—"
    cm = COUNT_RE.search(text)
    if cm:
        status = f"{status}({cm.group(2).strip()[:30]})"
    return {"id": eid, "tier": tier, "tags": tags, "keywords": "—", "rule": rule, "status": status}


def parse_entry_json(f: Path) -> dict:
    """JSON 正典條目:解析失敗直接拋(fail-loud)——寧可炸,不可讀錯。"""
    d = json.loads(f.read_text(encoding="utf-8"))
    counters = d.get("counters") or {}
    status = str(d.get("status", "—"))
    if counters:
        status += f"(seen {counters.get('seen', 0)} / applied {counters.get('applied', 0)})"
    return {
        "id": d.get("id", f.stem),
        "tier": d.get("tier", "shallow"),
        "tags": " ".join(d.get("tags", [])) or "—",
        "keywords": " ".join(d.get("keywords", []))[:60] or "—",
        "rule": str(d.get("rule", "—"))[:80],
        "status": status,
    }


def build_index(repo: Path) -> str | None:
    entries_dir = repo / "docs" / "knowledge" / "entries"
    if not entries_dir.is_dir():
        return None
    rows = []
    for f in sorted(entries_dir.glob("*.json")):
        try:
            rows.append(parse_entry_json(f))
        except json.JSONDecodeError as e:
            raise SystemExit(f"❌ {f} JSON 解析失敗(fail-loud,不猜不跳過):{e}")
    for f in sorted(entries_dir.glob("*.md")):  # 過渡期:舊 md 條目仍收錄
        rows.append(parse_entry(f))
    order = {"user-confirmed": 0, "deep": 1, "shallow": 2}
    rows.sort(key=lambda r: (order.get(r["tier"], 3), r["id"]))
    lines = [
        "# Knowledge INDEX(read this, not the entries you don't need)",
        "",
        GEN_MARK,
        "",
        "| id | tier | tags/scope | keywords | rule | status |",
        "|----|------|-----------|----------|------|--------|",
    ]
    for r in rows:
        lines.append(f"| {r['id']} | {r['tier']} | {r['tags']} | {r['keywords']} | {r['rule']} | {r['status']} |")
    lines += ["", f"_entries: {len(rows)} · regenerated: "
              f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')} (UTC+0)_", ""]
    return "\n".join(lines)


def strip_ts(text: str) -> str:
    return re.sub(r"_entries:.*", "", text).strip()


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=".")
    ap.add_argument("--check", action="store_true", help="只驗新鮮,不寫檔")
    args = ap.parse_args(argv[1:])
    repo = Path(args.repo).resolve()

    body = build_index(repo)
    if body is None:
        print("未偵測到 docs/knowledge/entries/(單檔模式)— 無事可做。")
        return 0
    index_path = repo / "docs" / "knowledge" / "INDEX.md"

    if args.check:
        if not index_path.is_file():
            print("❌ 拆檔模式但 docs/knowledge/INDEX.md 不存在 — 先跑本腳本生成。")
            return 1
        if strip_ts(index_path.read_text(encoding="utf-8", errors="ignore")) != strip_ts(body):
            print("❌ INDEX.md 已過期(與條目 metadata 不符)— 重跑 knowledge_index.py 再提交。")
            return 1
        print("✅ INDEX.md 新鮮(與條目一致)。")
        return 0

    index_path.write_text(body, encoding="utf-8")
    print(f"✅ 已重生 {index_path.relative_to(repo)}({body.count(chr(10))} 行)。")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
